title: Superalgos Documentation
description: The official documentation for the Superalgos Platform. Your comprehensive guide to the world's leading open-source crypto trading bot platform.
theme: jekyll-theme-minimal

# Google Analytics tracking ID (optional)
google_analytics: UA-XXXXX-X 